# Multidimentional Homogeneous Arrays

In [ ]:
# Typically called rectangular when lists are the same lenghth
[
    [1,2,3,4],
    [5,5,6,7]
]

[[1, 2, 3, 4], [5, 5, 6, 7]]

In [ ]:
# Multidimentional array

T= [
    [
    [1,2], [3,4], [5,6]
    ],
    [
    [7,8], [9,0], [1,3]
    ]
]

In [5]:
T

[[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 0], [1, 3]]]

In [6]:
# First thing in T - we use index:
T[0]

[[1, 2], [3, 4], [5, 6]]

In [7]:
# First thing inside first thing inside T:
T[0][0]

[1, 2]

In [8]:
# first index inside first list that is inside T
T[0][0][0]

1

## Homogeneous

In [ ]:
# Two-dimentional array
# This is NOT a Homogeneous data structure but a heterogenous data structure, because it contains 3 integers and one floating point element
[
    [1, 2.0],
    [3, 4],
]

[[1, 2.0], [3, 4]]

In [11]:
# Homogenoues
[
    [1, 2],
    [3, 4],
]

[[1, 2], [3, 4]]

# NumPy

In [13]:
# Numerical arrays
import numpy as np

In [14]:
# A 2D array of integers
X = np.array([[1, 2, 3], [4, 5, 6]])

# Show array
print(X)

[[1 2 3]
 [4 5 6]]


In [15]:
# Number of dimentions

print(X.ndim)

2


In [ ]:
# Shape
# Contains 2 rows and 3 clumns

print(X.shape)

(2, 3)


In [18]:
# Type of the elements

print(X.dtype)

int64


# Operations

In [22]:
# Two rrays

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

# Show
print('A:')
print(A)
print('B:')
print(B)

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]


In [24]:
# Adding constants
# Adds 5 to each element of the array
A + 5

array([[6, 7],
       [8, 9]])

In [ ]:
# Adding two arrays
# The first element of A added to the first element of B and so on
A + B

array([[ 6,  8],
       [10, 12]])

In [26]:
# Multyplying by constant
A * 2

array([[2, 4],
       [6, 8]])

In [28]:
# Multyplying two arrayas
A * B

array([[ 5, 12],
       [21, 32]])

In [31]:
# Matrix multiplication 
# Multiplying each row by each column, i.e.: 
#   1st element in the 1st row is multiplied by the 1st element in the 1st column (ex. 1*5 = 5)
#   then 2nd element in the 1st row is multiplied by the 2nd element in the 1st column (ex. 2*7 = 14)
#   then the above two added together (ex. 5+14 = 19)
A @ B

array([[19, 22],
       [43, 50]])

## Accessing Elements

In [37]:
# Recall A 
A

array([[1, 2],
       [3, 4]])

In [ ]:
# first row 
A[0]

array([1, 2])

In [ ]:
# Second element of the first row
A[0][1]

np.int64(2)

In [38]:
# Zeroth row, first column
A[0,1]

np.int64(2)

In [ ]:
# First column
# : means give me everything in that dimetion
# The below commans means >> give me every row,
#   but within the row, give me 1st elements (,0)
A[:,0]

array([2, 4])

## Slicing

In [40]:
# An array with lots of elements
X = np.arange(20)

# Show X
print(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [45]:
# Can contain 3 elements: (starting point, end, step)
# starting point - included,
# end point - excluded
# step
X = np.arange(10, 21, 3)

# Show X
print(X)

[10 13 16 19]


In [48]:
# Create again an array with lots elements
X = np.arange(20)

# Show X
print(X)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [50]:
# The 1st 5 elements (up to, but not including 5th elelemnt)
X[:5] # or X[0:5]

array([0, 1, 2, 3, 4])

In [51]:
# The next 5 things
X[5:10]

array([5, 6, 7, 8, 9])

In [52]:
# The elements from index 5 up (the length of the list or everything from 5 up)
X[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
# Every 2nd element
# Starting point not included defaults to 0
# End point not included defaults to len(X)


X[::2] # Would be same as X[0:len(X):2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])